[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = ["openzeppelin/=lib/openzeppelin-contracts"]
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
